### ISSUE TITLE
establish admin page

### ISSUE THREAD

**Issue by NashJ99** [astricklandd/unimportant-zebra#12]
current app goes to main page... `get to slash on app.js => index.ejs`

this main page should be the one for STUDENT KAYAK RENTER users. 

a link from here goes to admin page (with a sign in option soon) and then with admin function. 

This issue just to get the backend structure, pages, files all set up.

**Comment by barrycumbie** [comment]
https://github.com/barrycumbie/legendary-octo-journey/blob/main/utils/UserUtil.js
