### ISSUE TITLE
Create a wiki from the standup meeting with Cumbie.

### ISSUE THREAD

**Issue by Kiikz** [astricklandd/unimportant-zebra#13]

**Comment by astricklandd** [comment]
This meeting should be today, I or someone else there can take rough notes on a wiki during the meeting which can be revised before submission

**Comment by Kiikz** [comment]
https://github.com/astricklandd/unimportant-zebra/wiki/Sprint-2-Standup-Meeting

**Comment by Kiikz** [comment]
https://github.com/astricklandd/unimportant-zebra/wiki/Sprint-2-Standup-Meeting
