### ISSUE TITLE
Add Login for admin page and make users not allowed onto page if not logged in

### ISSUE THREAD

**Issue by AdamWarren01** [astricklandd/unimportant-zebra#23]
The login page exists.  Add a way for an admin user to add their login information to make sure they can't access the login page, if they cannot log in.

**Comment by astricklandd** [comment]
<img width="784" alt="Screen Shot 2022-11-28 at 2 16 56 PM" src="https://user-images.githubusercontent.com/111793985/204372549-059eafa1-0523-42d4-b0e0-af465e2fd9c0.png">

**Comment by astricklandd** [comment]
https://gorgeous-sweatsuit-calf.cyclic.app/

**Comment by astricklandd** [comment]
email: pluto@123
password: pluto1
--- 
create default admin creds for in class presentation
